version: '3'

services: 
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: adminmongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminmongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    links: 
      - mongo